# اسم سير العمل الذي سيظهر في تبويب Actions على GitHub
name: Build Windows Executable

# تحديد متى يتم تشغيل هذا الـ Action تلقائيًا
on:
  push:
    branches: [ "main" ] # يعمل عند أي عملية push لفرع main
  pull_request:
    branches: [ "main" ] # يعمل عند أي pull request لفرع main

# تحديد المهام التي سيتم تنفيذها
jobs:
  build:
    # تحديد نظام التشغيل الذي ستعمل عليه المهمة
    runs-on: windows-latest

    # تحديد الخطوات التي ستنفذ بالترتيب
    steps:
      # الخطوة 1: يقوم بسحب (checkout) الكود من المستودع الخاص بك إلى بيئة العمل
      - name: Checkout repository
        uses: actions/checkout@v4

      # الخطوة 2: إعداد بيئة بايثون
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          # يمكنك تحديد إصدار بايثون الذي تستخدمه
          python-version: '3.10'

      # الخطوة 3: تثبيت المكتبات المطلوبة من ملف requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # الخطوة 4: بناء الملف التنفيذي (.exe) باستخدام PyInstaller
      - name: Build executable with PyInstaller
        run: |
          python -m pip install pyinstaller
          python -m PyInstaller --name "BookletCreator" --onefile --windowed main.py

      # الخطوة 5: رفع الملف التنفيذي الناتج كـ "Artifact"
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          # اسم الملف الذي سيتم رفعه
          name: BookletCreator-Windows-Executable
          # مسار الملف التنفيذي الذي تم إنشاؤه
          path: dist/BookletCreator.exe
